name: test
on:
- push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        curl \
        --url https://api.github.com/repos/${{ github.repository }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json'
